# Generated by Django 5.1.7 on 2025-04-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="website",
            field=models.CharField(max_length=255),
        ),
    ]
