# Generated by Django 5.1.7 on 2025-04-26 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0008_purchaseorder_payment_method_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchaseorder",
            old_name="transaction_id",
            new_name="payment_id",
        ),
    ]
