# Generated by Django 5.1.7 on 2025-05-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0009_rename_transaction_id_purchaseorder_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="cashamount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
