# Generated by Django 5.1.7 on 2025-05-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0010_userprofile_cashamount"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="cashamount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
